### PR TITLE
Addressing issues table rewrites in TPCH-13 

### PR DESCRIPTION
**Pull request by edmondop**
This PR addresses the root cause for https://github.com/spiceai/spiceai/issues/1583. At the moment, the tests are failing with the following error:

Screenshot 2024-07-06 at 11 44 20 AM

I confirm the second quey runs correctly on the SpiceAI ui

### CODE REVIEW

**Comment by edmondop** [comment]
Further isolating the issue, the problem seems the following code:

```sql
(SELECT tpch.customers.c_custkey,
 "COUNT(tpch.orders.o_orderkey)" AS c_count FROM (SELECT tpch.customers.c_custkey, COUNT(tpch.orders.o_orderkey) FROM tpch.customers
```

So we have two options
- remove completely tpch prefix both for `c_custkey` and `COUNT(tpch.orders.o_orderkey)`
- alias both fields 

The manually created rewrite suggested by @phillipleblanc removes the qualifier from the first field and place an alias on the second:

```sql
(SELECT c_custkey AS c_custkey, "COUNT(tpch.orders.o_orderkey)" AS c_count FROM (SELECT tpch.customer.c_custkey, COUNT(tpch.orders.o_orderkey) AS "COUNT(tpch.orders.o_orderkey)" FROM tpch.customer
```

but it's probably also possible to alias both of them like so?

```sql
(SELECT "tpch.customer.c_custkey" AS c_custkey, "COUNT(tpch.orders.o_orderkey)" AS c_count FROM (SELECT tpch.customer.c_custkey as "tpch.customer.c_custkey", COUNT(tpch.orders.o_orderkey) AS "COUNT(tpch.orders.o_orderkey)" FROM tpch.customer
```

**Comment by phillipleblanc** [comment]
The alias probably isn't required if its just a column reference, but for expressions we need to alias them explicitly to the constructed DataFusion schema column.

Always aliasing to the DataFusion schema column name should work.

**Comment by phillipleblanc** [comment]
> So we have two options
>
> - remove completely tpch prefix both for c_custkey and COUNT(tpch.orders.o_orderkey)
> - alias both fields

The first one I don't think will work, because we can't rely on each source to come up with the same column name that DataFusion generates (i.e. `COUNT(tpch.orders.o_orderkey)`

**Comment by edmondop** [comment]
Further documenting here the process:

```
Sort: custdist DESC NULLS FIRST, c_orders.c_count DESC NULLS FIRST
  Projection: c_orders.c_count, COUNT(Int64(1)) AS custdist
    Aggregate: groupBy=[[c_orders.c_count]], aggr=[[COUNT(Int64(1))]]
      SubqueryAlias: c_orders
        Projection: tpch.customers.c_custkey, COUNT(tpch.orders.o_orderkey) AS c_count
          Projection: tpch.customers.c_custkey, COUNT(tpch.orders.o_orderkey)
            Aggregate: groupBy=[[tpch.customers.c_custkey]], aggr=[[COUNT(tpch.orders.o_orderkey)]]
              Left Join:  Filter: tpch.customers.c_custkey = tpch.orders.o_custkey AND tpch.orders.o_comment NOT LIKE Utf8("%special%requests%")
                TableScan: tpch.customers
                TableScan: tpch.orders
```

This is the current plan and as we traverse top to bottom, when we rewrite the expression of the top-level projection with aliases. However, this seems a bit of a hack and not a general purpose solution. Still investigating

**Comment by y-f-u** [comment]
@edmondop this is fixed in the linked PR: https://github.com/spiceai/datafusion/pull/17. Thanks for your input!

**Pull request closed without merging**
